name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and test
      run:  docker build . --file Dockerfile --tag docker-php-debug:test && docker run docker-php-debug:test bash /root/test.sh
